### PR TITLE
Add more Sidekiq and Ruby versions to test against

### PR DESCRIPTION
**Pull request by sponomarev**

### CODE REVIEW

**Comment by tibbon** [comment]
Can this be merged (and updated to include 2019 versions)?

**Comment by sponomarev** [comment]
@tibbon I'm not sure that the project is still maintained. 🤷‍♂️

**Comment by tibbon** [comment]
That's part of what I'm trying to figure out. We're otherwise considering using it, but it appears that some non-risky PRs have been un-merged, so... that worries me, and makes me think maybe to stay away unless there's some more active work allowed here. Unmaintained gems are instant tech-debt for me.

**Comment by deanpcmad** [comment]
Hey, thanks for your PR! I've just taken over this project/gem and am going through the PRs and issues. 
GitHub Actions is now being used for CI so if you have time to update this PR for that, it would be appreciated but I'll close it in the mean time.

**Pull request closed without merging**
